# This is a config for E2B sandbox template.
# You can use template ID (uwypx8m5bmfz61ewmqxc) or template name (lovable-clone-testv2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lovable-clone-testv2") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-clone-testv2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-clone-testv2')

team_id = "417e49ab-451d-47d3-9439-88ae4c153614"
start_cmd = "bash /compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-clone-testv2"
template_id = "uwypx8m5bmfz61ewmqxc"
